sudo: required
language: node_js
node_js:
  - "6.9.1"
cache:
  directories:
    - node_modules # NPM packages
install:
  - npm install
  - sudo pip install awscli
script:
  - npm run docs:build
  - docs:publish

env:
    global:
        - DEPLOY_BRANCH="source"
        - SOURCE_DIR="_book"
        - TARGET_BRANCH="gh-pages"
        - SSH_KEY="id_rsa"
        - GIT_NAME="travis"
        - GIT_EMAIL="deploy@travis-ci.org"

branches:
  only:
    - source
    - auto
notifications:
  email: false
