sudo: required
language: node_js
node_js:
  - "6.9.1"
cache:
  directories:
    - node_modules # NPM packages
install:
  - npm install
  - sudo pip install awscli
script:
  - npm run docs:build
  # If the build is not a PR and is on source branch, deploy the GitBook to S3.
  - | 
      if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "source" ]]; then
        echo "so far so good"
        aws s3 sync --acl public-read --delete _book/ s3://rusoto.org
      fi
    # TODO: cloudfront invalidation

branches:
  except:
    - master
