sudo: required
language: node_js
node_js:
- 6.9.1
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run docs:build
- node_modules/.bin/gh-pages-travis
env:
  global:
  - DEPLOY_BRANCH="master"
  - SOURCE_DIR="_book"
  - TARGET_BRANCH="gh-pages"
  - SSH_KEY="id_rsa"
  - GIT_NAME="travis"
  - GIT_EMAIL="deploy@travis-ci.org"
branches:
  only:
  - master
  - auto
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_6853688af28a_key -iv $encrypted_6853688af28a_iv
  -in id_rsa.enc -out id_rsa -d
