language: node_js
node_js:
  - "6.9.1"
install:
  - npm install
script:
  - npm run docs:build
after_success:
  # If the build is not a PR and is on master, deploy the GitBook to gh-pages.
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "source" &&
    bash publish.sh
env:
  global:
    secure: A9GHiWLFIKk6Dx+RXzaz6lHxmmEBITpRqnK27VI6R4mEL6fNoZQiLWp6P674FXccRjPtuBI0+tSnO6zmSvP6uTxJ95CnaKaoAeQI0hhzanPl8xYsRCq9adNOfw1QpfH89vlRUBq3UJPQ0eMq4ukKM6SZrKhuM7/5tZqE8hAJkchnlKkoiBYWvDucFDOdqrQzDkeTEJ7oSJapVmoea5eRn5sFjtHmiYpQGfKJ0bEPbEBwtJv1GWdcNk93f4WV6eoV1uPTSJ9HWnyUgFvYxfGvsj/fE2gwtwBaUe5v3rH+ok4Jw7zcrmrL6NDM4WSxfF9y+llleWPxZm/L5XP0lQIGLFrRu9e0S8LCt+61LAM04miV4AhoKjfyWbCXLLu8HnRks6eb0sDdUOKdb8VcQtaaAhAf1Qvi98iphPru7de2uRspQvQSsl1G8KnQaFUt3vWScmu2vgdcEVR5xSdyrE5Zt15cAHyyU1M4p8oBVrbUE06C27XzOFD+7rQ4X9YJsOCisfgi3LgeYTQurjHgPQT6/bpwIzKnpHaOp275w1SK7KLQyWAs7gs459QLOqWAtV15Huz0MI0bsv3+zZDmo3j98gz96inVZK7oBjqgX+5m2JymWdE8kPauYWqfPQKJfuawAjURFjqjPhOrjhNKiFw0/r3YuVRctuStcI45BYokQJ0=
branches:
  except:
    - master
