language: node_js
node_js:
  - "6.9.1"
cache:
  directories:
    - node_modules # NPM packages
install:
  - npm install
  - pip install awscli
script:
  - npm run docs:build
after_success:
  # If the build is not a PR and is on source branch, deploy the GitBook to S3.
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "source" &&
    aws s3 sync --acl public-read --delete _book/ s3://rusoto.org
    # TODO: cloudfront invalidation

branches:
  except:
    - master
